Small bug fixes
Dragonsight91/Demon-Overlord pull request #74
Opened 2021-01-07 22:01 UTC by Natshirt

Fixes issue #67 
* Removed double occurrence of `eat` in `DemonOverlord/config/interactions.config`
* Too long user messages by invoking interaction command are sliced and no longer throw exceptions
* Too many user mentions by invoking interaction commands no longer throw exceptions. Stop adding mentions to list when limit is reached
* Last change might need a review

2021-01-07 23:44 UTC, Dragonsight91 requested changes
All in all a decent chunk of change, idea of using the nested function was creative and actually a pretty intelligent idea. just change the mentioned things and it should be good to go.

2021-01-07 23:44 UTC, Dragonsight91 commented on DemonOverlord/core/modules/interactions.py
> +        # nested function to get mentions of command and make sure
mmmh unfinished comment? do finish your sandwiches please ^^

2021-01-07 23:44 UTC, Dragonsight91 commented on DemonOverlord/core/modules/interactions.py
> +                    len(combine_interactions[command.action]["emoji"])
do remember that the emoji in the interactions is not what will actually be shown. it is only a key for the dict `Config.emojis` which holds instances of `discord.emoji` please change this to reflect that, otherwise this will create a bug since `Yay` as emote gets sent as `<:Yay:796364510956355584>` which is much longer. This needs to be changed.

2021-01-07 23:44 UTC, Dragonsight91 commented on DemonOverlord/core/modules/interactions.py
> +                    len(social_interactions[command.action]["emoji"])
same as previous, please change to reflect the actual emote string length instead of the emote search value length

2021-01-08 16:02 UTC, Natshirt commented
Applied the requested change

2021-01-08 17:08 UTC, Dragonsight91 approved these changes
Seems good to go, all changes approved

2021-01-08 17:08 UTC, merged