Patched minesweeper
Dragonsight91/Demon-Overlord pull request #93
Opened 2021-08-12 11:57 UTC by NattCaat

- Uncovered zero fields are no longer shown as exploded mines
- Increased timeout from 1 minute to 3 minutes
- Small changes in documentation

2021-08-13 08:32 UTC, Dragonsight91 requested changes
mostly good, few suggestions, see comments

2021-08-13 08:32 UTC, Dragonsight91 commented on DemonOverlord/config/cmd_info.json
> +                "description": "Play a game of minesweeper\nTo start a game, use 'minesweeper start'\nFurther instruction are given during game",
maybe give the user a hint in both the game embed and the command description, that there's a 3 min time window for inputs. That way users can't complain about not knowing the time they have

2021-08-13 08:32 UTC, Dragonsight91 commented on DemonOverlord/core/modules/minesweeper.py
> +                    "message", check=msg_test, timeout=180
maybe use this value and plonk it into the embed somehow...

2021-08-21 09:29 UTC, NattCaat commented
Player gets notified that there is a time window for inputs in game embed. I have not figured out yet, how to integrate it in the help embed

2021-08-22 10:52 UTC, Dragonsight91 approved these changes
Seems fine to me it has my approval
will be merged now

2021-08-22 10:52 UTC, merged